### ISSUE TITLE
makefile toolcheck

### ISSUE THREAD

**Issue by nick-youngblut** [jiarong/SSUsearch#1]
I ran into a SyntaxError when running toolcheck:
"""
File "<stdin>", line 1
    -e try: import sys,pandas,scipy,matplotlib,screed
         ^
SyntaxError: invalid syntax
"""

Also, toolcheck isn't exiting mcclust. It looked liked it was hanging, but just needed user input of [enter] to quit, but then didn't produce the '**\* Dependencies are installed' message.

**Comment by jiarong** [comment]
The bug was fixed a while (4 months) ago. Sorry that I forgot to reply here.
