### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by homopolymer** [jiarong/SSUsearch#2]
An unexpected error occurs when run test example.  Error messages are as follows.

(ssusearch_pyenv)fzeng@g01:~/Tool/MetagenomeTools/SSUsearch$ make -f Makefile Seqfiles="test/data/1c.fa test/data/1d.fa test/data/2c.fa test/data/2d.fa" Design=test/SS.design Script_dir=./scripts SSUsearch_db=./data/SSUsearch_db Method=ssusearch_no_qc Method=ssusearch_no_qc Hmmsearch=$HMMSEARCH_BIN Mothur=$MOTHUR_BIN Flash=$FLASH_BIN Mcclust_jar=$MCCLUST_JAR
**\* Dependencies are installed
mkdir -p /home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa.ssu.out/
make -f /home/fzeng/Tool/MetagenomeTools/SSUsearch/scripts/ssusearch.Makefile  \
  Seqfile=/home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa -C /home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa.ssu.out/ Tag=dummy Cpu=1
make[1]: Entering directory `/home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa.ssu.out'
Realfile=/home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa \
&& if file $Realfile | grep -q "gzip compressed data" ; \
   then zcat /home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa > dummy.qc; \
   elif file $Realfile | grep -q "bzip2 compressed data"; \
   then bzcat /home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa > dummy.qc; \
   else ln -sf /home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa dummy.qc; \
   fi;

**\* Starting hmmsearch
time /home/fzeng/Tool/MetagenomeTools/SSUsearch/external_tools/hmmer-3.1b1-linux-intel-x86_64/binaries/hmmsearch --incE 10 --incdomE 10 --cpu 1 \
    -A dummy.qc.ssu.sto \
    -o dummy.qc.ssu.hmmout \
    --tblout dummy.qc.ssu.hmmtblout \
    --domtblout dummy.qc.ssu.hmmdomtblout \
    /home/fzeng/Tool/MetagenomeTools/SSUsearch/data/SSUsearch_db/Hmm.ssu.hmm dummy.qc
make[1]: time: Command not found
make[1]: **\* [hmmsearch] Error 127
make[1]: Leaving directory `/home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa.ssu.out'
make: **\* [/home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa.ssu.out/dummy.qc.ssu.align.filter] Error 2

**Comment by homopolymer** [comment]
I remove 'time' and run again.  New error comes out.

(ssusearch_pyenv)fzeng@g01:~/Tool/MetagenomeTools/SSUsearch$ srun -w c03 make -f Makefile Seqfiles="test/data/1c.fa test/data/1d.fa test/data/2c.fa test/data/2d.fa" Design=test/SS.design Script_dir=./scripts SSUsearch_db=./data/SSUsearch_db Method=ssusearch_no_qc Method=ssusearch_no_qc Hmmsearch=$HMMSEARCH_BIN Mothur=$MOTHUR_BIN Flash=$FLASH_BIN Mcclust_jar=$MCCLUST_JAR Cpu=1
**\* Dependencies are installed
mkdir -p /home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa.ssu.out/
make -f /home/fzeng/Tool/MetagenomeTools/SSUsearch/scripts/ssusearch.Makefile  \
  Seqfile=/home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa -C /home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa.ssu.out/ Tag=dummy Cpu=1
make[1]: Entering directory `/home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa.ssu.out'
Realfile=/home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa \
&& if file $Realfile | grep -q "gzip compressed data" ; \
   then zcat /home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa > dummy.qc; \
   elif file $Realfile | grep -q "bzip2 compressed data"; \
   then bzcat /home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa > dummy.qc; \
   else ln -sf /home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa dummy.qc; \
   fi;

**\* Starting hmmsearch
/home/fzeng/Tool/MetagenomeTools/SSUsearch/external_tools/hmmer-3.1b1-linux-intel-x86_64/binaries/hmmsearch --incE 10 --incdomE 10 --cpu 1 \
    -A dummy.qc.ssu.sto \
    -o dummy.qc.ssu.hmmout \
    --tblout dummy.qc.ssu.hmmtblout \
    --domtblout dummy.qc.ssu.hmmdomtblout \
    /home/fzeng/Tool/MetagenomeTools/SSUsearch/data/SSUsearch_db/Hmm.ssu.hmm dummy.qc
hmmsearch done..
python /home/fzeng/Tool/MetagenomeTools/SSUsearch/scripts/get-seq-from-hmmtblout.py \
    dummy.qc.ssu.hmmtblout \
    dummy.qc.ssu.sto \
    dummy.qc.ssu \
|| { rm -f dummy.qc.ssu && exit 1; }
50 hits at 10 cutoff
Traceback (most recent call last):
  File "/home/fzeng/Tool/MetagenomeTools/SSUsearch/scripts/get-seq-from-hmmtblout.py", line 113, in <module>
    main()
  File "/home/fzeng/Tool/MetagenomeTools/SSUsearch/scripts/get-seq-from-hmmtblout.py", line 103, in main
    for n, record in enumerate(screed.open(sys.argv[2])):
  File "/home/fzeng/Tool/MetagenomeTools/SSUsearch/external_tools/ssusearch_pyenv/lib/python2.7/site-packages/screed/openscreed.py", line 48, in **init**
    self.iter_fn = self.open_reader(filename, _args, *_kwargs)
  File "/home/fzeng/Tool/MetagenomeTools/SSUsearch/external_tools/ssusearch_pyenv/lib/python2.7/site-packages/screed/openscreed.py", line 104, in open_reader
    raise ValueError("unknown file format for '%s'" % filename)
ValueError: unknown file format for 'dummy.qc.ssu.sto'
make[1]: Leaving directory `/home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa.ssu.out'
make[1]: **\* [hmmsearch] Error 1
make: **\* [/home/fzeng/Tool/MetagenomeTools/SSUsearch/test/data/1c.fa.ssu.out/dummy.qc.ssu.align.filter] Error 2

**Comment by jiarong** [comment]
Please use the tutorial version instead. The Makefile version is not maintained anymore.

**Comment by etheleon** [comment]
Hi jiarong, 

am I right to say version 115 of SILVA was used to build the HMMs?

From aem.asm.org/content/82/1/157.long:

> We quality trimmed SILVA (7) SSU and LSU Ref NR database (version 115) sequences by discarding all sequences with ambiguous DNA bases and converting U to T. 

And the representative sequences from [SSUsearch_db.tar.gz ](https://s3.amazonaws.com/ssusearchdb/SSUsearch_db.tgz) were from 108? 

> Gene_db.silva_108_rep_set.fasta
> Gene_db.silva_108_rep_set.8mer

If that is true, what is the rationale for using different versions?

**Comment by jiarong** [comment]
The rationale is that we try not to re-invent if there are existing resources:

For HMMs, we could not find any so had to built the HMMs with the most updated SIVLA (version 115) at that time.
For the representative sequences, QIIME had such databases maintained (from SIVLA 108 at that time) so we just use those from them.
