### ISSUE TITLE
outdated database

### ISSUE THREAD

**Issue by Sanrrone** [jiarong/SSUsearch#3]
Dears, how can I updated the databases?, the files in SSUsearch_db are crossed and I don't know which raw data from silva use. (same case from hmm).

there are a way to update the database?

regards

**Comment by jiarong** [comment]
The SILVA seed alignment is pretty stable and HMM performance is fairly stable with different version of SILVA, so there is no need to update those two.

You might want to update classification databases( Gene_tax.*.tax, and Gene_db.*.fasta). SSUsearch references are compatible with mothur. I recommend downloading from [mothur site](https://www.mothur.org/wiki/Silva_reference_files). If you download from SILVA, you need to parse the taxonomy string from descriptions field in fasta files.
